server:
  port: 32769

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
